# Generated by Django 5.2.15 on 2026-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='prenom',
        ),
        migrations.AddField(
            model_name='inscription',
            name='nom_prenom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Nom & Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
