# Generated by Django 4.2 on 2026-06-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuaire', '0002_remove_inscription_email_remove_inscription_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
